import type { StickerDef } from './types';

export const STICKER_LIBRARY: StickerDef[] = [
  // ===== ANIMALS =====
  // Pets
  { id: 's-dog', emoji: '🐶', name: 'Puppy', category: 'Animals' },
  { id: 's-cat', emoji: '🐱', name: 'Kitty', category: 'Animals' },
  { id: 's-hamster', emoji: '🐹', name: 'Hamster', category: 'Animals' },
  { id: 's-bunny', emoji: '🐰', name: 'Bunny', category: 'Animals' },
  { id: 's-mouse', emoji: '🐭', name: 'Mouse', category: 'Animals' },
  { id: 's-parrot', emoji: '🦜', name: 'Parrot', category: 'Animals' },
  { id: 's-fish', emoji: '🐠', name: 'Tropical Fish', category: 'Animals' },
  { id: 's-turtle', emoji: '🐢', name: 'Turtle', category: 'Animals' },
  { id: 's-goldfish', emoji: '🐟', name: 'Fish', category: 'Animals' },
  { id: 's-poodle', emoji: '🐩', name: 'Poodle', category: 'Animals' },
  // Wild
  { id: 's-unicorn', emoji: '🦄', name: 'Unicorn', category: 'Animals' },
  { id: 's-butterfly', emoji: '🦋', name: 'Butterfly', category: 'Animals' },
  { id: 's-dolphin', emoji: '🐬', name: 'Dolphin', category: 'Animals' },
  { id: 's-panda', emoji: '🐼', name: 'Panda', category: 'Animals' },
  { id: 's-owl', emoji: '🦉', name: 'Owl', category: 'Animals' },
  { id: 's-lion', emoji: '🦁', name: 'Lion', category: 'Animals' },
  { id: 's-elephant', emoji: '🐘', name: 'Elephant', category: 'Animals' },
  { id: 's-giraffe', emoji: '🦒', name: 'Giraffe', category: 'Animals' },
  { id: 's-monkey', emoji: '🐵', name: 'Monkey', category: 'Animals' },
  { id: 's-fox', emoji: '🦊', name: 'Fox', category: 'Animals' },
  { id: 's-penguin', emoji: '🐧', name: 'Penguin', category: 'Animals' },
  { id: 's-koala', emoji: '🐨', name: 'Koala', category: 'Animals' },
  { id: 's-bear', emoji: '🐻', name: 'Bear', category: 'Animals' },
  { id: 's-polar-bear', emoji: '🐻‍❄️', name: 'Polar Bear', category: 'Animals' },
  { id: 's-whale', emoji: '🐋', name: 'Whale', category: 'Animals' },
  { id: 's-octopus', emoji: '🐙', name: 'Octopus', category: 'Animals' },
  { id: 's-ladybug', emoji: '🐞', name: 'Ladybug', category: 'Animals' },
  { id: 's-bee', emoji: '🐝', name: 'Bee', category: 'Animals' },
  { id: 's-dragon', emoji: '🐉', name: 'Dragon', category: 'Animals' },
  { id: 's-t-rex', emoji: '🦖', name: 'T-Rex', category: 'Animals' },
  { id: 's-sauropod', emoji: '🦕', name: 'Sauropod', category: 'Animals' },
  { id: 's-shark', emoji: '🦈', name: 'Shark', category: 'Animals' },
  { id: 's-flamingo', emoji: '🦩', name: 'Flamingo', category: 'Animals' },
  { id: 's-frog', emoji: '🐸', name: 'Frog', category: 'Animals' },
  { id: 's-tiger', emoji: '🐯', name: 'Tiger', category: 'Animals' },
  { id: 's-zebra', emoji: '🦓', name: 'Zebra', category: 'Animals' },
  { id: 's-gorilla', emoji: '🦍', name: 'Gorilla', category: 'Animals' },
  { id: 's-hippo', emoji: '🦛', name: 'Hippo', category: 'Animals' },
  { id: 's-rhino', emoji: '🦏', name: 'Rhino', category: 'Animals' },
  { id: 's-crocodile', emoji: '🐊', name: 'Crocodile', category: 'Animals' },
  { id: 's-snake', emoji: '🐍', name: 'Snake', category: 'Animals' },
  { id: 's-lizard', emoji: '🦎', name: 'Lizard', category: 'Animals' },
  { id: 's-eagle', emoji: '🦅', name: 'Eagle', category: 'Animals' },
  { id: 's-peacock', emoji: '🦚', name: 'Peacock', category: 'Animals' },
  { id: 's-swan', emoji: '🦢', name: 'Swan', category: 'Animals' },
  { id: 's-dove', emoji: '🕊️', name: 'Dove', category: 'Animals' },
  { id: 's-bat', emoji: '🦇', name: 'Bat', category: 'Animals' },
  { id: 's-scorpion', emoji: '🦂', name: 'Scorpion', category: 'Animals' },
  { id: 's-snail', emoji: '🐌', name: 'Snail', category: 'Animals' },
  { id: 's-caterpillar', emoji: '🐛', name: 'Caterpillar', category: 'Animals' },
  { id: 's-ant', emoji: '🐜', name: 'Ant', category: 'Animals' },
  { id: 's-crab', emoji: '🦀', name: 'Crab', category: 'Animals' },
  { id: 's-lobster', emoji: '🦞', name: 'Lobster', category: 'Animals' },
  { id: 's-hedgehog', emoji: '🦔', name: 'Hedgehog', category: 'Animals' },
  { id: 's-raccoon', emoji: '🦝', name: 'Raccoon', category: 'Animals' },
  { id: 's-sloth', emoji: '🦥', name: 'Sloth', category: 'Animals' },
  { id: 's-otter', emoji: '🦦', name: 'Otter', category: 'Animals' },
  { id: 's-deer', emoji: '🦌', name: 'Deer', category: 'Animals' },
  { id: 's-wolf', emoji: '🐺', name: 'Wolf', category: 'Animals' },
  { id: 's-horse', emoji: '🐴', name: 'Horse', category: 'Animals' },
  { id: 's-pig', emoji: '🐷', name: 'Pig', category: 'Animals' },
  { id: 's-cow', emoji: '🐮', name: 'Cow', category: 'Animals' },
  { id: 's-chicken', emoji: '🐔', name: 'Chicken', category: 'Animals' },
  { id: 's-duck', emoji: '🦆', name: 'Duck', category: 'Animals' },
  { id: 's-chick', emoji: '🐥', name: 'Baby Chick', category: 'Animals' },
  { id: 's-jellyfish', emoji: '🪼', name: 'Jellyfish', category: 'Animals' },
  { id: 's-seal', emoji: '🦭', name: 'Seal', category: 'Animals' },

  // ===== STARS & SPARKLE =====
  { id: 's-star', emoji: '⭐', name: 'Gold Star', category: 'Stars' },
  { id: 's-glowing', emoji: '🌟', name: 'Glowing Star', category: 'Stars' },
  { id: 's-sparkles', emoji: '✨', name: 'Sparkles', category: 'Stars' },
  { id: 's-rainbow', emoji: '🌈', name: 'Rainbow', category: 'Stars' },
  { id: 's-heart', emoji: '❤️', name: 'Red Heart', category: 'Stars' },
  { id: 's-pink-heart', emoji: '💖', name: 'Sparkling Heart', category: 'Stars' },
  { id: 's-orange-heart', emoji: '🧡', name: 'Orange Heart', category: 'Stars' },
  { id: 's-yellow-heart', emoji: '💛', name: 'Yellow Heart', category: 'Stars' },
  { id: 's-green-heart', emoji: '💚', name: 'Green Heart', category: 'Stars' },
  { id: 's-blue-heart', emoji: '💙', name: 'Blue Heart', category: 'Stars' },
  { id: 's-purple-heart', emoji: '💜', name: 'Purple Heart', category: 'Stars' },
  { id: 's-white-heart', emoji: '🤍', name: 'White Heart', category: 'Stars' },
  { id: 's-black-heart', emoji: '🖤', name: 'Black Heart', category: 'Stars' },
  { id: 's-growing-heart', emoji: '💗', name: 'Growing Heart', category: 'Stars' },
  { id: 's-revolving-hearts', emoji: '💞', name: 'Revolving Hearts', category: 'Stars' },
  { id: 's-heart-deco', emoji: '💟', name: 'Heart Decoration', category: 'Stars' },
  { id: 's-diamond', emoji: '💎', name: 'Diamond', category: 'Stars' },
  { id: 's-crown', emoji: '👑', name: 'Crown', category: 'Stars' },
  { id: 's-fire', emoji: '🔥', name: 'Fire', category: 'Stars' },
  { id: 's-bolt', emoji: '⚡', name: 'Lightning', category: 'Stars' },
  { id: 's-comet', emoji: '☄️', name: 'Comet', category: 'Stars' },
  { id: 's-dizzy', emoji: '💫', name: 'Dizzy Star', category: 'Stars' },
  { id: 's-magic', emoji: '🪄', name: 'Magic Wand', category: 'Stars' },
  { id: 's-crystal', emoji: '🔮', name: 'Crystal Ball', category: 'Stars' },
  { id: 's-gem', emoji: '💍', name: 'Ring', category: 'Stars' },
  { id: 's-star-struck', emoji: '🌠', name: 'Shooting Star', category: 'Stars' },
  { id: 's-snow-globe', emoji: '🎐', name: 'Wind Chime', category: 'Stars' },
  { id: 's-yarn', emoji: '🧶', name: 'Yarn Ball', category: 'Stars' },

  // ===== FOOD & TREATS =====
  { id: 's-pizza', emoji: '🍕', name: 'Pizza', category: 'Food' },
  { id: 's-icecream', emoji: '🍦', name: 'Ice Cream', category: 'Food' },
  { id: 's-cookie', emoji: '🍪', name: 'Cookie', category: 'Food' },
  { id: 's-cupcake', emoji: '🧁', name: 'Cupcake', category: 'Food' },
  { id: 's-donut', emoji: '🍩', name: 'Donut', category: 'Food' },
  { id: 's-watermelon', emoji: '🍉', name: 'Watermelon', category: 'Food' },
  { id: 's-strawberry', emoji: '🍓', name: 'Strawberry', category: 'Food' },
  { id: 's-cherry', emoji: '🍒', name: 'Cherries', category: 'Food' },
  { id: 's-grapes', emoji: '🍇', name: 'Grapes', category: 'Food' },
  { id: 's-banana', emoji: '🍌', name: 'Banana', category: 'Food' },
  { id: 's-apple', emoji: '🍎', name: 'Apple', category: 'Food' },
  { id: 's-green-apple', emoji: '🍏', name: 'Green Apple', category: 'Food' },
  { id: 's-peach', emoji: '🍑', name: 'Peach', category: 'Food' },
  { id: 's-pineapple', emoji: '🍍', name: 'Pineapple', category: 'Food' },
  { id: 's-mango', emoji: '🥭', name: 'Mango', category: 'Food' },
  { id: 's-blueberries', emoji: '🫐', name: 'Blueberries', category: 'Food' },
  { id: 's-coconut', emoji: '🥥', name: 'Coconut', category: 'Food' },
  { id: 's-avocado', emoji: '🥑', name: 'Avocado', category: 'Food' },
  { id: 's-lollipop', emoji: '🍭', name: 'Lollipop', category: 'Food' },
  { id: 's-candy', emoji: '🍬', name: 'Candy', category: 'Food' },
  { id: 's-chocolate', emoji: '🍫', name: 'Chocolate', category: 'Food' },
  { id: 's-cake', emoji: '🎂', name: 'Birthday Cake', category: 'Food' },
  { id: 's-shortcake', emoji: '🍰', name: 'Shortcake', category: 'Food' },
  { id: 's-pie', emoji: '🥧', name: 'Pie', category: 'Food' },
  { id: 's-pancakes', emoji: '🥞', name: 'Pancakes', category: 'Food' },
  { id: 's-waffle', emoji: '🧇', name: 'Waffle', category: 'Food' },
  { id: 's-taco', emoji: '🌮', name: 'Taco', category: 'Food' },
  { id: 's-burrito', emoji: '🌯', name: 'Burrito', category: 'Food' },
  { id: 's-burger', emoji: '🍔', name: 'Burger', category: 'Food' },
  { id: 's-hotdog', emoji: '🌭', name: 'Hot Dog', category: 'Food' },
  { id: 's-fries', emoji: '🍟', name: 'Fries', category: 'Food' },
  { id: 's-popcorn', emoji: '🍿', name: 'Popcorn', category: 'Food' },
  { id: 's-sushi', emoji: '🍣', name: 'Sushi', category: 'Food' },
  { id: 's-ramen', emoji: '🍜', name: 'Ramen', category: 'Food' },
  { id: 's-dumpling', emoji: '🥟', name: 'Dumpling', category: 'Food' },
  { id: 's-pretzel', emoji: '🥨', name: 'Pretzel', category: 'Food' },
  { id: 's-cheese', emoji: '🧀', name: 'Cheese', category: 'Food' },
  { id: 's-egg', emoji: '🥚', name: 'Egg', category: 'Food' },
  { id: 's-bacon', emoji: '🥓', name: 'Bacon', category: 'Food' },
  { id: 's-bubble-tea', emoji: '🧋', name: 'Bubble Tea', category: 'Food' },
  { id: 's-juice', emoji: '🧃', name: 'Juice Box', category: 'Food' },
  { id: 's-smoothie', emoji: '🥤', name: 'Smoothie', category: 'Food' },
  { id: 's-honey', emoji: '🍯', name: 'Honey', category: 'Food' },
  { id: 's-shaved-ice', emoji: '🍧', name: 'Shaved Ice', category: 'Food' },
  { id: 's-popsicle', emoji: '🧊', name: 'Ice Cube', category: 'Food' },

  // ===== SPORTS & ACTIVITIES =====
  { id: 's-soccer', emoji: '⚽', name: 'Soccer', category: 'Sports' },
  { id: 's-basketball', emoji: '🏀', name: 'Basketball', category: 'Sports' },
  { id: 's-football', emoji: '🏈', name: 'Football', category: 'Sports' },
  { id: 's-baseball', emoji: '⚾', name: 'Baseball', category: 'Sports' },
  { id: 's-tennis', emoji: '🎾', name: 'Tennis', category: 'Sports' },
  { id: 's-volleyball', emoji: '🏐', name: 'Volleyball', category: 'Sports' },
  { id: 's-rugby', emoji: '🏉', name: 'Rugby', category: 'Sports' },
  { id: 's-cricket', emoji: '🏏', name: 'Cricket', category: 'Sports' },
  { id: 's-hockey', emoji: '🏒', name: 'Hockey', category: 'Sports' },
  { id: 's-lacrosse', emoji: '🥍', name: 'Lacrosse', category: 'Sports' },
  { id: 's-badminton', emoji: '🏸', name: 'Badminton', category: 'Sports' },
  { id: 's-trophy', emoji: '🏆', name: 'Trophy', category: 'Sports' },
  { id: 's-medal', emoji: '🥇', name: 'Gold Medal', category: 'Sports' },
  { id: 's-silver-medal', emoji: '🥈', name: 'Silver Medal', category: 'Sports' },
  { id: 's-bronze-medal', emoji: '🥉', name: 'Bronze Medal', category: 'Sports' },
  { id: 's-muscle', emoji: '💪', name: 'Strong', category: 'Sports' },
  { id: 's-rocket', emoji: '🚀', name: 'Rocket', category: 'Sports' },
  { id: 's-skateboard', emoji: '🛹', name: 'Skateboard', category: 'Sports' },
  { id: 's-bike', emoji: '🚲', name: 'Bicycle', category: 'Sports' },
  { id: 's-swim', emoji: '🏊', name: 'Swimming', category: 'Sports' },
  { id: 's-martial-arts', emoji: '🥋', name: 'Martial Arts', category: 'Sports' },
  { id: 's-bowling', emoji: '🎳', name: 'Bowling', category: 'Sports' },
  { id: 's-ping-pong', emoji: '🏓', name: 'Ping Pong', category: 'Sports' },
  { id: 's-ski', emoji: '⛷️', name: 'Skiing', category: 'Sports' },
  { id: 's-surfing', emoji: '🏄', name: 'Surfing', category: 'Sports' },
  { id: 's-boxing', emoji: '🥊', name: 'Boxing', category: 'Sports' },
  { id: 's-climbing', emoji: '🧗', name: 'Climbing', category: 'Sports' },
  { id: 's-gymnastics', emoji: '🤸', name: 'Gymnastics', category: 'Sports' },
  { id: 's-running', emoji: '🏃', name: 'Running', category: 'Sports' },
  { id: 's-weight', emoji: '🏋️', name: 'Weightlifting', category: 'Sports' },
  { id: 's-yoga', emoji: '🧘', name: 'Yoga', category: 'Sports' },
  { id: 's-archery', emoji: '🏹', name: 'Archery', category: 'Sports' },
  { id: 's-fishing', emoji: '🎣', name: 'Fishing', category: 'Sports' },
  { id: 's-ice-skate', emoji: '⛸️', name: 'Ice Skating', category: 'Sports' },
  { id: 's-snowboard', emoji: '🏂', name: 'Snowboard', category: 'Sports' },
  { id: 's-roller-skate', emoji: '🛼', name: 'Roller Skate', category: 'Sports' },
  { id: 's-scooter', emoji: '🛴', name: 'Scooter', category: 'Sports' },

  // ===== NATURE =====
  { id: 's-flower', emoji: '🌸', name: 'Cherry Blossom', category: 'Nature' },
  { id: 's-sunflower', emoji: '🌻', name: 'Sunflower', category: 'Nature' },
  { id: 's-rose', emoji: '🌹', name: 'Rose', category: 'Nature' },
  { id: 's-tulip', emoji: '🌷', name: 'Tulip', category: 'Nature' },
  { id: 's-hibiscus', emoji: '🌺', name: 'Hibiscus', category: 'Nature' },
  { id: 's-bouquet', emoji: '💐', name: 'Bouquet', category: 'Nature' },
  { id: 's-blossom', emoji: '🌼', name: 'Blossom', category: 'Nature' },
  { id: 's-lotus', emoji: '🪷', name: 'Lotus', category: 'Nature' },
  { id: 's-tree', emoji: '🌳', name: 'Tree', category: 'Nature' },
  { id: 's-evergreen', emoji: '🌲', name: 'Evergreen', category: 'Nature' },
  { id: 's-palm', emoji: '🌴', name: 'Palm Tree', category: 'Nature' },
  { id: 's-cactus', emoji: '🌵', name: 'Cactus', category: 'Nature' },
  { id: 's-mushroom', emoji: '🍄', name: 'Mushroom', category: 'Nature' },
  { id: 's-clover', emoji: '🍀', name: 'Four Leaf Clover', category: 'Nature' },
  { id: 's-leaf', emoji: '🍃', name: 'Leaf', category: 'Nature' },
  { id: 's-maple-leaf', emoji: '🍁', name: 'Maple Leaf', category: 'Nature' },
  { id: 's-fallen-leaf', emoji: '🍂', name: 'Fallen Leaf', category: 'Nature' },
  { id: 's-herb', emoji: '🌿', name: 'Herb', category: 'Nature' },
  { id: 's-seedling', emoji: '🌱', name: 'Seedling', category: 'Nature' },
  { id: 's-bamboo', emoji: '🎍', name: 'Bamboo', category: 'Nature' },
  { id: 's-sun', emoji: '☀️', name: 'Sunshine', category: 'Nature' },
  { id: 's-moon', emoji: '🌙', name: 'Moon', category: 'Nature' },
  { id: 's-full-moon', emoji: '🌕', name: 'Full Moon', category: 'Nature' },
  { id: 's-earth', emoji: '🌍', name: 'Earth', category: 'Nature' },
  { id: 's-earth-am', emoji: '🌎', name: 'Americas', category: 'Nature' },
  { id: 's-earth-as', emoji: '🌏', name: 'Asia', category: 'Nature' },
  { id: 's-snowflake', emoji: '❄️', name: 'Snowflake', category: 'Nature' },
  { id: 's-snowman', emoji: '⛄', name: 'Snowman', category: 'Nature' },
  { id: 's-ocean', emoji: '🌊', name: 'Wave', category: 'Nature' },
  { id: 's-volcano', emoji: '🌋', name: 'Volcano', category: 'Nature' },
  { id: 's-mountain', emoji: '🏔️', name: 'Mountain', category: 'Nature' },
  { id: 's-sunrise', emoji: '🌅', name: 'Sunrise', category: 'Nature' },
  { id: 's-sunset', emoji: '🌇', name: 'Sunset', category: 'Nature' },
  { id: 's-milky-way-n', emoji: '🌌', name: 'Night Sky', category: 'Nature' },
  { id: 's-cloud', emoji: '☁️', name: 'Cloud', category: 'Nature' },
  { id: 's-raindrop', emoji: '💧', name: 'Raindrop', category: 'Nature' },
  { id: 's-tornado', emoji: '🌪️', name: 'Tornado', category: 'Nature' },
  { id: 's-umbrella', emoji: '☂️', name: 'Umbrella', category: 'Nature' },
  { id: 's-shell', emoji: '🐚', name: 'Shell', category: 'Nature' },
  { id: 's-coral', emoji: '🪸', name: 'Coral', category: 'Nature' },
  { id: 's-feather', emoji: '🪶', name: 'Feather', category: 'Nature' },
  { id: 's-nest', emoji: '🪹', name: 'Nest', category: 'Nature' },

  // ===== FUN & CELEBRATION =====
  { id: 's-party', emoji: '🎉', name: 'Party', category: 'Fun' },
  { id: 's-balloon', emoji: '🎈', name: 'Balloon', category: 'Fun' },
  { id: 's-gift', emoji: '🎁', name: 'Gift', category: 'Fun' },
  { id: 's-music-note', emoji: '🎵', name: 'Music', category: 'Fun' },
  { id: 's-art-palette', emoji: '🎨', name: 'Art', category: 'Fun' },
  { id: 's-clap', emoji: '👏', name: 'Clap', category: 'Fun' },
  { id: 's-thumbsup', emoji: '👍', name: 'Thumbs Up', category: 'Fun' },
  { id: 's-hundred', emoji: '💯', name: 'Perfect', category: 'Fun' },
  { id: 's-confetti', emoji: '🎊', name: 'Confetti', category: 'Fun' },
  { id: 's-fireworks', emoji: '🎆', name: 'Fireworks', category: 'Fun' },
  { id: 's-sparkler', emoji: '🎇', name: 'Sparkler', category: 'Fun' },
  { id: 's-disco', emoji: '🪩', name: 'Disco Ball', category: 'Fun' },
  { id: 's-pinata', emoji: '🪅', name: 'Pinata', category: 'Fun' },
  { id: 's-teddy', emoji: '🧸', name: 'Teddy Bear', category: 'Fun' },
  { id: 's-kite', emoji: '🪁', name: 'Kite', category: 'Fun' },
  { id: 's-gamepad', emoji: '🎮', name: 'Video Game', category: 'Fun' },
  { id: 's-puzzle', emoji: '🧩', name: 'Puzzle', category: 'Fun' },
  { id: 's-dice', emoji: '🎲', name: 'Dice', category: 'Fun' },
  { id: 's-carousel', emoji: '🎠', name: 'Carousel', category: 'Fun' },
  { id: 's-ferris', emoji: '🎡', name: 'Ferris Wheel', category: 'Fun' },
  { id: 's-roller-coaster', emoji: '🎢', name: 'Roller Coaster', category: 'Fun' },
  { id: 's-circus', emoji: '🎪', name: 'Circus Tent', category: 'Fun' },
  { id: 's-slot', emoji: '🎰', name: 'Jackpot', category: 'Fun' },
  { id: 's-bowling-pin', emoji: '🎳', name: 'Bowling', category: 'Fun' },
  { id: 's-joystick', emoji: '🕹️', name: 'Joystick', category: 'Fun' },
  { id: 's-chess', emoji: '♟️', name: 'Chess', category: 'Fun' },
  { id: 's-yo-yo', emoji: '🪀', name: 'Yo-Yo', category: 'Fun' },
  { id: 's-sled', emoji: '🛷', name: 'Sled', category: 'Fun' },
  { id: 's-magic-8ball', emoji: '🎱', name: '8 Ball', category: 'Fun' },
  { id: 's-bubbles', emoji: '🫧', name: 'Bubbles', category: 'Fun' },

  // ===== FACES & EXPRESSIONS =====
  { id: 's-star-eyes', emoji: '🤩', name: 'Star Eyes', category: 'Faces' },
  { id: 's-sunglasses', emoji: '😎', name: 'Cool', category: 'Faces' },
  { id: 's-wink', emoji: '😉', name: 'Wink', category: 'Faces' },
  { id: 's-hug', emoji: '🤗', name: 'Hug', category: 'Faces' },
  { id: 's-smile', emoji: '😊', name: 'Happy', category: 'Faces' },
  { id: 's-grin', emoji: '😁', name: 'Grin', category: 'Faces' },
  { id: 's-laugh', emoji: '😂', name: 'Laughing', category: 'Faces' },
  { id: 's-rofl', emoji: '🤣', name: 'Rolling', category: 'Faces' },
  { id: 's-kiss', emoji: '😘', name: 'Kiss', category: 'Faces' },
  { id: 's-angel', emoji: '😇', name: 'Angel', category: 'Faces' },
  { id: 's-nerd', emoji: '🤓', name: 'Nerd', category: 'Faces' },
  { id: 's-party-face', emoji: '🥳', name: 'Party Face', category: 'Faces' },
  { id: 's-mind-blown', emoji: '🤯', name: 'Mind Blown', category: 'Faces' },
  { id: 's-salute', emoji: '🫡', name: 'Salute', category: 'Faces' },
  { id: 's-peace', emoji: '✌️', name: 'Peace', category: 'Faces' },
  { id: 's-flex', emoji: '🦾', name: 'Robot Arm', category: 'Faces' },
  { id: 's-love-eyes', emoji: '😍', name: 'Heart Eyes', category: 'Faces' },
  { id: 's-thinking', emoji: '🤔', name: 'Thinking', category: 'Faces' },
  { id: 's-shush', emoji: '🤫', name: 'Shushing', category: 'Faces' },
  { id: 's-chef-kiss', emoji: '🤌', name: "Chef's Kiss", category: 'Faces' },
  { id: 's-clown-face', emoji: '🤡', name: 'Clown', category: 'Faces' },
  { id: 's-cowboy', emoji: '🤠', name: 'Cowboy', category: 'Faces' },
  { id: 's-monocle', emoji: '🧐', name: 'Monocle', category: 'Faces' },
  { id: 's-zany', emoji: '🤪', name: 'Zany', category: 'Faces' },
  { id: 's-money-face', emoji: '🤑', name: 'Money Face', category: 'Faces' },
  { id: 's-relieved', emoji: '😌', name: 'Relieved', category: 'Faces' },
  { id: 's-smirk', emoji: '😏', name: 'Smirk', category: 'Faces' },
  { id: 's-tongue', emoji: '😜', name: 'Tongue Out', category: 'Faces' },
  { id: 's-yum', emoji: '😋', name: 'Yum', category: 'Faces' },
  { id: 's-innocent', emoji: '🥰', name: 'In Love', category: 'Faces' },

  // ===== TRAVEL & VEHICLES =====
  { id: 's-airplane', emoji: '✈️', name: 'Airplane', category: 'Travel' },
  { id: 's-car', emoji: '🚗', name: 'Car', category: 'Travel' },
  { id: 's-race-car', emoji: '🏎️', name: 'Race Car', category: 'Travel' },
  { id: 's-bus', emoji: '🚌', name: 'Bus', category: 'Travel' },
  { id: 's-train', emoji: '🚂', name: 'Train', category: 'Travel' },
  { id: 's-bullet-train', emoji: '🚄', name: 'Bullet Train', category: 'Travel' },
  { id: 's-ship', emoji: '🚢', name: 'Ship', category: 'Travel' },
  { id: 's-sailboat', emoji: '⛵', name: 'Sailboat', category: 'Travel' },
  { id: 's-canoe', emoji: '🛶', name: 'Canoe', category: 'Travel' },
  { id: 's-ufo', emoji: '🛸', name: 'UFO', category: 'Travel' },
  { id: 's-helicopter', emoji: '🚁', name: 'Helicopter', category: 'Travel' },
  { id: 's-hot-air', emoji: '🎈', name: 'Balloon Ride', category: 'Travel' },
  { id: 's-compass', emoji: '🧭', name: 'Compass', category: 'Travel' },
  { id: 's-tent', emoji: '⛺', name: 'Camping', category: 'Travel' },
  { id: 's-castle', emoji: '🏰', name: 'Castle', category: 'Travel' },
  { id: 's-beach', emoji: '🏖️', name: 'Beach', category: 'Travel' },
  { id: 's-world-map', emoji: '🗺️', name: 'World Map', category: 'Travel' },
  { id: 's-fire-truck', emoji: '🚒', name: 'Fire Truck', category: 'Travel' },
  { id: 's-ambulance', emoji: '🚑', name: 'Ambulance', category: 'Travel' },
  { id: 's-police-car', emoji: '🚓', name: 'Police Car', category: 'Travel' },
  { id: 's-taxi', emoji: '🚕', name: 'Taxi', category: 'Travel' },
  { id: 's-motorcycle', emoji: '🏍️', name: 'Motorcycle', category: 'Travel' },
  { id: 's-tractor', emoji: '🚜', name: 'Tractor', category: 'Travel' },
  { id: 's-construction', emoji: '🚧', name: 'Construction', category: 'Travel' },
  { id: 's-lighthouse', emoji: '🗼', name: 'Tower', category: 'Travel' },
  { id: 's-ferris-t', emoji: '🎡', name: 'Ferris Wheel', category: 'Travel' },
  { id: 's-national-park', emoji: '🏞️', name: 'National Park', category: 'Travel' },
  { id: 's-stadium', emoji: '🏟️', name: 'Stadium', category: 'Travel' },

  // ===== SPACE & SCIENCE =====
  { id: 's-astronaut', emoji: '👨‍🚀', name: 'Astronaut', category: 'Space' },
  { id: 's-planet', emoji: '🪐', name: 'Saturn', category: 'Space' },
  { id: 's-telescope', emoji: '🔭', name: 'Telescope', category: 'Space' },
  { id: 's-alien', emoji: '👽', name: 'Alien', category: 'Space' },
  { id: 's-robot', emoji: '🤖', name: 'Robot', category: 'Space' },
  { id: 's-dna', emoji: '🧬', name: 'DNA', category: 'Space' },
  { id: 's-atom', emoji: '⚛️', name: 'Atom', category: 'Space' },
  { id: 's-microscope', emoji: '🔬', name: 'Microscope', category: 'Space' },
  { id: 's-lab', emoji: '🧪', name: 'Test Tube', category: 'Space' },
  { id: 's-magnet', emoji: '🧲', name: 'Magnet', category: 'Space' },
  { id: 's-satellite', emoji: '🛰️', name: 'Satellite', category: 'Space' },
  { id: 's-milky-way', emoji: '🌌', name: 'Galaxy', category: 'Space' },
  { id: 's-rocket-ship', emoji: '🚀', name: 'Rocket Ship', category: 'Space' },
  { id: 's-moon-face', emoji: '🌝', name: 'Moon Face', category: 'Space' },
  { id: 's-sun-face', emoji: '🌞', name: 'Sun Face', category: 'Space' },
  { id: 's-globe', emoji: '🌐', name: 'Globe', category: 'Space' },
  { id: 's-battery', emoji: '🔋', name: 'Battery', category: 'Space' },
  { id: 's-bulb', emoji: '💡', name: 'Light Bulb', category: 'Space' },
  { id: 's-gear', emoji: '⚙️', name: 'Gear', category: 'Space' },
  { id: 's-wrench', emoji: '🔧', name: 'Wrench', category: 'Space' },
  { id: 's-computer', emoji: '💻', name: 'Laptop', category: 'Space' },
  { id: 's-phone', emoji: '📱', name: 'Phone', category: 'Space' },

  // ===== MUSIC & ARTS =====
  { id: 's-guitar', emoji: '🎸', name: 'Guitar', category: 'Arts' },
  { id: 's-piano', emoji: '🎹', name: 'Piano', category: 'Arts' },
  { id: 's-drum', emoji: '🥁', name: 'Drum', category: 'Arts' },
  { id: 's-violin', emoji: '🎻', name: 'Violin', category: 'Arts' },
  { id: 's-trumpet', emoji: '🎺', name: 'Trumpet', category: 'Arts' },
  { id: 's-saxophone', emoji: '🎷', name: 'Saxophone', category: 'Arts' },
  { id: 's-banjo', emoji: '🪕', name: 'Banjo', category: 'Arts' },
  { id: 's-accordion', emoji: '🪗', name: 'Accordion', category: 'Arts' },
  { id: 's-maracas', emoji: '🪇', name: 'Maracas', category: 'Arts' },
  { id: 's-microphone', emoji: '🎤', name: 'Microphone', category: 'Arts' },
  { id: 's-headphones', emoji: '🎧', name: 'Headphones', category: 'Arts' },
  { id: 's-palette', emoji: '🎨', name: 'Palette', category: 'Arts' },
  { id: 's-crayon', emoji: '🖍️', name: 'Crayon', category: 'Arts' },
  { id: 's-paintbrush', emoji: '🖌️', name: 'Paintbrush', category: 'Arts' },
  { id: 's-pen', emoji: '🖊️', name: 'Pen', category: 'Arts' },
  { id: 's-camera', emoji: '📷', name: 'Camera', category: 'Arts' },
  { id: 's-video-cam', emoji: '📹', name: 'Video Camera', category: 'Arts' },
  { id: 's-movie', emoji: '🎬', name: 'Movie', category: 'Arts' },
  { id: 's-theater', emoji: '🎭', name: 'Theater', category: 'Arts' },
  { id: 's-book', emoji: '📚', name: 'Books', category: 'Arts' },
  { id: 's-pencil', emoji: '✏️', name: 'Pencil', category: 'Arts' },
  { id: 's-notebook', emoji: '📓', name: 'Notebook', category: 'Arts' },
  { id: 's-frame', emoji: '🖼️', name: 'Picture Frame', category: 'Arts' },
  { id: 's-scroll', emoji: '📜', name: 'Scroll', category: 'Arts' },
  { id: 's-scissors', emoji: '✂️', name: 'Scissors', category: 'Arts' },
  { id: 's-thread', emoji: '🧵', name: 'Thread', category: 'Arts' },
  { id: 's-knitting', emoji: '🧶', name: 'Knitting', category: 'Arts' },

  // ===== FANTASY & MAGIC =====
  { id: 's-fairy', emoji: '🧚', name: 'Fairy', category: 'Fantasy' },
  { id: 's-mermaid', emoji: '🧜‍♀️', name: 'Mermaid', category: 'Fantasy' },
  { id: 's-merman', emoji: '🧜‍♂️', name: 'Merman', category: 'Fantasy' },
  { id: 's-superhero', emoji: '🦸', name: 'Superhero', category: 'Fantasy' },
  { id: 's-supervillain', emoji: '🦹', name: 'Supervillain', category: 'Fantasy' },
  { id: 's-wizard', emoji: '🧙', name: 'Wizard', category: 'Fantasy' },
  { id: 's-ninja', emoji: '🥷', name: 'Ninja', category: 'Fantasy' },
  { id: 's-princess', emoji: '👸', name: 'Princess', category: 'Fantasy' },
  { id: 's-prince', emoji: '🤴', name: 'Prince', category: 'Fantasy' },
  { id: 's-ghost', emoji: '👻', name: 'Ghost', category: 'Fantasy' },
  { id: 's-jack-o', emoji: '🎃', name: 'Pumpkin', category: 'Fantasy' },
  { id: 's-genie', emoji: '🧞', name: 'Genie', category: 'Fantasy' },
  { id: 's-vampire', emoji: '🧛', name: 'Vampire', category: 'Fantasy' },
  { id: 's-zombie', emoji: '🧟', name: 'Zombie', category: 'Fantasy' },
  { id: 's-elf', emoji: '🧝', name: 'Elf', category: 'Fantasy' },
  { id: 's-troll', emoji: '🧌', name: 'Troll', category: 'Fantasy' },
  { id: 's-skull', emoji: '💀', name: 'Skull', category: 'Fantasy' },
  { id: 's-pirate-flag', emoji: '🏴‍☠️', name: 'Pirate', category: 'Fantasy' },
  { id: 's-crystal-2', emoji: '🔮', name: 'Fortune', category: 'Fantasy' },
  { id: 's-potion', emoji: '🧪', name: 'Potion', category: 'Fantasy' },
  { id: 's-magic-wand', emoji: '🪄', name: 'Magic', category: 'Fantasy' },
  { id: 's-broom', emoji: '🧹', name: 'Flying Broom', category: 'Fantasy' },
  { id: 's-eye', emoji: '👁️', name: 'All-Seeing Eye', category: 'Fantasy' },
  { id: 's-dragon-face', emoji: '🐲', name: 'Dragon Face', category: 'Fantasy' },

  // ===== SYMBOLS & BADGES =====
  { id: 's-checkmark', emoji: '✅', name: 'Check', category: 'Symbols' },
  { id: 's-bullseye', emoji: '🎯', name: 'Bullseye', category: 'Symbols' },
  { id: 's-ribbon', emoji: '🎀', name: 'Ribbon', category: 'Symbols' },
  { id: 's-medal-military', emoji: '🎖️', name: 'Military Medal', category: 'Symbols' },
  { id: 's-shield', emoji: '🛡️', name: 'Shield', category: 'Symbols' },
  { id: 's-key', emoji: '🔑', name: 'Key', category: 'Symbols' },
  { id: 's-old-key', emoji: '🗝️', name: 'Old Key', category: 'Symbols' },
  { id: 's-bell', emoji: '🔔', name: 'Bell', category: 'Symbols' },
  { id: 's-megaphone', emoji: '📣', name: 'Megaphone', category: 'Symbols' },
  { id: 's-flag', emoji: '🚩', name: 'Flag', category: 'Symbols' },
  { id: 's-checkered-flag', emoji: '🏁', name: 'Checkered Flag', category: 'Symbols' },
  { id: 's-trophy-cup', emoji: '🏅', name: 'Sports Medal', category: 'Symbols' },
  { id: 's-swords', emoji: '⚔️', name: 'Swords', category: 'Symbols' },
  { id: 's-infinity', emoji: '♾️', name: 'Infinity', category: 'Symbols' },
  { id: 's-recycle', emoji: '♻️', name: 'Recycle', category: 'Symbols' },
  { id: 's-trident', emoji: '🔱', name: 'Trident', category: 'Symbols' },
  { id: 's-anchor', emoji: '⚓', name: 'Anchor', category: 'Symbols' },
  { id: 's-peace-sym', emoji: '☮️', name: 'Peace Symbol', category: 'Symbols' },
  { id: 's-yin-yang', emoji: '☯️', name: 'Yin Yang', category: 'Symbols' },
  { id: 's-exclamation', emoji: '❗', name: 'Exclamation', category: 'Symbols' },
  { id: 's-question', emoji: '❓', name: 'Question', category: 'Symbols' },
  { id: 's-bangbang', emoji: '‼️', name: 'Double Bang', category: 'Symbols' },
  { id: 's-100-sym', emoji: '💯', name: '100 Points', category: 'Symbols' },
  { id: 's-new', emoji: '🆕', name: 'New', category: 'Symbols' },
  { id: 's-free', emoji: '🆓', name: 'Free', category: 'Symbols' },
  { id: 's-cool', emoji: '🆒', name: 'Cool', category: 'Symbols' },
  { id: 's-up', emoji: '🆙', name: 'Up!', category: 'Symbols' },
  { id: 's-ok', emoji: '🆗', name: 'OK', category: 'Symbols' },

  // ===== HANDS & GESTURES =====
  { id: 's-wave', emoji: '👋', name: 'Wave', category: 'Hands' },
  { id: 's-raised-hand', emoji: '✋', name: 'High Five', category: 'Hands' },
  { id: 's-ok-hand', emoji: '👌', name: 'OK Hand', category: 'Hands' },
  { id: 's-pinch', emoji: '🤏', name: 'Pinch', category: 'Hands' },
  { id: 's-victory', emoji: '✌️', name: 'Victory', category: 'Hands' },
  { id: 's-crossed-fingers', emoji: '🤞', name: 'Fingers Crossed', category: 'Hands' },
  { id: 's-love-you', emoji: '🤟', name: 'Love You', category: 'Hands' },
  { id: 's-rock-on', emoji: '🤘', name: 'Rock On', category: 'Hands' },
  { id: 's-call-me', emoji: '🤙', name: 'Call Me', category: 'Hands' },
  { id: 's-point-up', emoji: '☝️', name: 'Point Up', category: 'Hands' },
  { id: 's-thumbs-down', emoji: '👎', name: 'Thumbs Down', category: 'Hands' },
  { id: 's-fist', emoji: '✊', name: 'Fist', category: 'Hands' },
  { id: 's-fist-bump', emoji: '🤜', name: 'Fist Bump', category: 'Hands' },
  { id: 's-pray', emoji: '🙏', name: 'Thank You', category: 'Hands' },
  { id: 's-handshake', emoji: '🤝', name: 'Handshake', category: 'Hands' },
  { id: 's-nail-polish', emoji: '💅', name: 'Nail Polish', category: 'Hands' },
  { id: 's-writing', emoji: '✍️', name: 'Writing', category: 'Hands' },
  { id: 's-open-hands', emoji: '🤲', name: 'Open Hands', category: 'Hands' },
  { id: 's-palms-up', emoji: '🫴', name: 'Palms Up', category: 'Hands' },
  { id: 's-heart-hands', emoji: '🫶', name: 'Heart Hands', category: 'Hands' },
];

export const STICKER_CATEGORIES = [...new Set(STICKER_LIBRARY.map((s) => s.category))];

export function getStickerById(id: string): StickerDef | undefined {
  return STICKER_LIBRARY.find((s) => s.id === id);
}
